name: CI Workflow

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["dev"]

env:
  PYTHON_VERSION: '3.14'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync && uv add flake8

      - name: Run Flake8 linter
        run: uv run flake8 ./src

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync && uv add pytest

      - name: Run tests
        run: uv run pytest
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync && uv add bandit

      - name: Run Bandit security scan
        run: uv run bandit app/*.py -f json -o bandit_report.json -n 3 -lll

      - name: Upload Bandit report
        uses: actions/upload-artifact@v7
        with:
          name: bandit-report
          path: bandit_report.json
